services:
  database:
    image: postgres:16
    container_name: database_con
    environment:
      POSTGRES_USER: app_admin
      POSTGRES_PASSWORD: SuperSecret123
      POSTGRES_DB: gamification
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U app_admin -d gamification" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - dev-net

  backend:
    build:
      context: ./backend-api
    container_name: backend_con
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://app_admin:SuperSecret123@database:5432/gamification
      SECRET_KEY: DEVSECOPS
    ports:
      - "5000:5000"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - dev-net

  frontend:
    build:
      context: ./frontend-app
    container_name: frontend_con
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - dev-net

  jenkins:
    build:
      context: ./devops-infra/jenkins
    container_name: jenkins_con
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - dev-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_con
    ports:
      - "9090:9090"
    volumes:
      - ./devops-infra/monitoring/prometheus/local_prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - dev-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_con
    ports:
      - "3000:3000"
    volumes:
      - ./devops-infra/monitoring/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - dev-net

networks:
  dev-net:
    driver: bridge

volumes:
  jenkins_home:
